#!/bin/csh 

setenv SCR /wrk/hdstaff/dpefour/support/Olympus/scripts

# ./doit_k7

# ./doit_k8

# Edit CSV files to comment out the headers

# Remove the timing arcs that have already been waived and generate new file ultrascale.filtered_arcs.csv
# ${SCR}/filterWaivedArcs -i ultrascale.all.arcs.csv -o ultrascale.NOPATHFOUND_01132014.csv -w WAIVER_checkDSP48E1Arcs_01132014.csv -v
${SCR}/filterWaivedArcs -i ultrascale.all.arcs.csv -o ultrascale.NOPATHFOUND_02042014.csv -w WAIVER_checkDSP48E1Arcs_02042014.csv -v
# ${SCR}/filterWaivedArcs -i ultrascale.NOPATHFOUND_01132014.csv -o ultrascale.KNOWNISSUES_01132014.csv -w KNOWNISSUES_checkDSP48E1Arcs_01132014.csv -v -invert

foreach CSV (*all.arcs.csv)
  echo " Processing $CSV"
  set CSV_OK =  `echo -n $CSV | sed -e 's/\.all/\.OK/g'`
  grep -v ',"mismatch",' $CSV | grep -v ',"no path found",' > $CSV_OK
  set CSV_FAILED =  `echo -n $CSV | sed -e 's/\.all/\.FAILED/g'`
  grep -v ',"OK",' $CSV > $CSV_FAILED
end

foreach CSV (*csv)
  echo " Processing $CSV"
  set RPT =  `echo -n $CSV | sed -e 's/\.csv/\.rpt/g'`
  ${SCR}/csv2tbl -csv $CSV -out $RPT
end

exit 0
